version: "3.7"
services:
  app:
    container_name: backend
    image: jupyter/pyspark-notebook
    command: bash -c "pip install -r requirements.txt && jupyter notebook"
    links:
      - postgres
    ports:
      - "8888:8888"
      - "8502:8501"
    volumes:
      - ./:/home/jovyan
    networks:
      - jnet
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 5g
    tty: true
  
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
     - "5432:5432"
    networks:
      - jnet
    restart: unless-stopped

networks:
  jnet:
    driver: bridge